//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woopin.SGC.Services.Afip.wsContribuyenteN10 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://awshomo.afip.gov.ar/padron-puc-ws/services/select.ContribuyenteNivel10Sel" +
        "ectServiceImpl", ConfigurationName="wsContribuyenteN10.ContribuyenteNivel10SelectServiceImpl")]
    public interface ContribuyenteNivel10SelectServiceImpl {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://select.services.server.ws.impl.puc.padron.afip.gov) of message getRequest does not match the default value (https://awshomo.afip.gov.ar/padron-puc-ws/services/select.ContribuyenteNivel10SelectServiceImpl)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Woopin.SGC.Services.Afip.wsContribuyenteN10.getResponse get(Woopin.SGC.Services.Afip.wsContribuyenteN10.getRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Woopin.SGC.Services.Afip.wsContribuyenteN10.getResponse> getAsync(Woopin.SGC.Services.Afip.wsContribuyenteN10.getRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get", WrapperNamespace="http://select.services.server.ws.impl.puc.padron.afip.gov", IsWrapped=true)]
    public partial class getRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string pContribuyentePK;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string pToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string pSign;
        
        public getRequest() {
        }
        
        public getRequest(string pContribuyentePK, string pToken, string pSign) {
            this.pContribuyentePK = pContribuyentePK;
            this.pToken = pToken;
            this.pSign = pSign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResponse", WrapperNamespace="https://awshomo.afip.gov.ar/padron-puc-ws/services/select.ContribuyenteNivel10Sel" +
        "ectServiceImpl", IsWrapped=true)]
    public partial class getResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getReturn;
        
        public getResponse() {
        }
        
        public getResponse(string getReturn) {
            this.getReturn = getReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContribuyenteNivel10SelectServiceImplChannel : Woopin.SGC.Services.Afip.wsContribuyenteN10.ContribuyenteNivel10SelectServiceImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContribuyenteNivel10SelectServiceImplClient : System.ServiceModel.ClientBase<Woopin.SGC.Services.Afip.wsContribuyenteN10.ContribuyenteNivel10SelectServiceImpl>, Woopin.SGC.Services.Afip.wsContribuyenteN10.ContribuyenteNivel10SelectServiceImpl {
        
        public ContribuyenteNivel10SelectServiceImplClient() {
        }
        
        public ContribuyenteNivel10SelectServiceImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContribuyenteNivel10SelectServiceImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContribuyenteNivel10SelectServiceImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContribuyenteNivel10SelectServiceImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Woopin.SGC.Services.Afip.wsContribuyenteN10.getResponse Woopin.SGC.Services.Afip.wsContribuyenteN10.ContribuyenteNivel10SelectServiceImpl.get(Woopin.SGC.Services.Afip.wsContribuyenteN10.getRequest request) {
            return base.Channel.get(request);
        }
        
        public string get(string pContribuyentePK, string pToken, string pSign) {
            Woopin.SGC.Services.Afip.wsContribuyenteN10.getRequest inValue = new Woopin.SGC.Services.Afip.wsContribuyenteN10.getRequest();
            inValue.pContribuyentePK = pContribuyentePK;
            inValue.pToken = pToken;
            inValue.pSign = pSign;
            Woopin.SGC.Services.Afip.wsContribuyenteN10.getResponse retVal = ((Woopin.SGC.Services.Afip.wsContribuyenteN10.ContribuyenteNivel10SelectServiceImpl)(this)).get(inValue);
            return retVal.getReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Woopin.SGC.Services.Afip.wsContribuyenteN10.getResponse> Woopin.SGC.Services.Afip.wsContribuyenteN10.ContribuyenteNivel10SelectServiceImpl.getAsync(Woopin.SGC.Services.Afip.wsContribuyenteN10.getRequest request) {
            return base.Channel.getAsync(request);
        }
        
        public System.Threading.Tasks.Task<Woopin.SGC.Services.Afip.wsContribuyenteN10.getResponse> getAsync(string pContribuyentePK, string pToken, string pSign) {
            Woopin.SGC.Services.Afip.wsContribuyenteN10.getRequest inValue = new Woopin.SGC.Services.Afip.wsContribuyenteN10.getRequest();
            inValue.pContribuyentePK = pContribuyentePK;
            inValue.pToken = pToken;
            inValue.pSign = pSign;
            return ((Woopin.SGC.Services.Afip.wsContribuyenteN10.ContribuyenteNivel10SelectServiceImpl)(this)).getAsync(inValue);
        }
    }
}
